export {
  formatUploadBytes,
  MAX_PRODUCT_ATTACHMENT_UPLOAD_BYTES,
  MAX_PRODUCT_IMAGE_UPLOAD_BYTES,
  MAX_PRODUCT_UPLOAD_JSON_BODY,
  MAX_PRODUCT_VIDEO_UPLOAD_BYTES,
  PRODUCT_ATTACHMENT_UPLOAD_HINT,
  PRODUCT_IMAGE_MAX_EDGE,
  PRODUCT_IMAGE_UPLOAD_HINT,
  PRODUCT_IMAGE_WEBP_QUALITY,
  PRODUCT_VIDEO_UPLOAD_HINT,
} from '../../shared/product-media-upload-limits.js';
