export {
  formatMonthlyProductionLabel,
  formatPpmLabel,
  inferMonthlyProductionLabelFromRicohModelName,
  inferMonthlyProductionPagesFromRicohModelName,
  inferPpmDigitsFromRicohModelName,
  inferPpmLabelFromRicohModelName,
  inferProduccionTierFromMonthlyPages,
  inferProduccionTierFromRicohModelName,
  inferRicohModelNumberBlock,
  isMultifuncionalNuevaOSeminueva,
  isRicohImMpCatalogEquipment,
  resolveMultifuncionalVelocidadFromModel,
  resolveRicohMonthlyProductionFromModel,
} from '../../shared/ricoh-model-ppm.js';
